version: '3'

services:
  app:
    image: expense-logger-app
    build:
      context: .
      dockerfile: Dockerfile-app
    expose:
      - "5000"
  nginx:
    image: expense-logger-nginx
    build:
      context: .
      dockerfile: Dockerfile-nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app