version: '3'

services:
  app:
    restart: always
  nginx:
    restart: always
    build:
      args:
        IS_PRODUCTION: "true"
    volumes:
      - web-ssl-challange:/var/www/certbot
      - ssl-certificates:/etc/letsencrypt
  certbot:
    image: certbot/certbot
    container_name: expense-logger-certbot
    volumes:
      - web-ssl-challange:/var/www/certbot
      - ssl-certificates:/etc/letsencrypt
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/certbot --email ${EMAIL} --agree-tos --no-eff-email --force-renewal -d ${DOMAIN}

volumes:
  web-ssl-challange:
  ssl-certificates:
    driver: local
    driver_opts:
      type: none
      device: ${PATH_CERTIFICATES}
      o: bind