version: '3'

services:
  app:
    image: expense-logger-app
    build:
      context: .
      dockerfile: app.Dockerfile
    expose:
      - "5000"
  nginx:
    image: expense-logger-nginx
    build:
      context: .
      dockerfile: nginx.Dockerfile
      args:
        EMAIL: ${EMAIL}
        DOMAIN: ${DOMAIN}
    ports:
      - 80:80
      - 443:443
    volumes:
      - web-root:/var/www/certbot
    depends_on:
      - app
    environment:
      DOMAIN: ${DOMAIN}

volumes:
  certbot-etc:
  web-root: