version: '3'

services:
  app:
    image: ${IMAGE_REPOSITORY}/expense-logger-app:${IMAGE_VERSION}
    container_name: expense-logger-app
    build:
      context: .
      dockerfile: app.Dockerfile
    expose:
      - "5000"
    command: "uwsgi --ini app.ini"
  nginx:
    image: ${IMAGE_REPOSITORY}/expense-logger-nginx:${IMAGE_VERSION}
    container_name: expense-logger-nginx
    build:
      context: .
      dockerfile: nginx.Dockerfile
      args:
        EMAIL: ${EMAIL}
        DOMAIN: ${DOMAIN}
    environment:
      DOMAIN: ${DOMAIN}
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app