FROM nginx:latest

RUN rm /etc/nginx/conf.d/default.conf

COPY ./docker/nginx-compose.conf /etc/nginx/conf.d/default.conf
COPY ./docker/self-signed.conf ./docker/ssl-params.conf /etc/nginx/snippets/

RUN openssl req -x509 -nodes -days 365 -newkey rsa:2048 \
  -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt \
  -subj "" \
  -addext ""

RUN openssl dhparam -out /etc/ssl/certs/dhparam.pem 2048