version: '3'

services:
  app:
    environment:
      FLASK_ENV: development
    volumes:
      - ./:/app
    command: "uwsgi --ini docker/app.ini --py-autoreload 1"
  nginx:
    image: ${IMAGE_REPOSITORY}/expense-logger-nginx:${IMAGE_VERSION}-local
    build:
      args:
        DOMAIN: localhost
    environment:
      DOMAIN: localhost